server:
  port: 7088
  servlet:
    context-path: /jufeng/api

spring:
  application:
    name: jufeng-backend
  profiles:
    active: dev

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 日志配置
logging:
  level:
    com.jufeng: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/jufeng.log

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/jufeng_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: jufeng
    password: Leilei*0217
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.jufeng: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://121.36.91.199:3306/jufeng_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: jufeng
    password: Leilei*0217
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.jufeng: INFO
    root: WARN

