name: deploy_master_jufeng_back
on:
  push:
    branches:
      - master

jobs:
  master-jufeng-back:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Flyway Clean
        if: ${{ vars.FLYWAY_CLEAN == '1' }}
        run: mvn flyway:clean -P prod
      - name: Build application jufeng_back
        run: mvn flyway:repair -P prod && mvn flyway:migrate -P prod && mvn jooq-codegen:generate -P prod && mvn clean compile -P prod && mvn install -P prod -Dmaven.test.skip=true
      - name: Scp jar To HW Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HW_TEST_SERVER }}
          username: ${{ secrets.HW_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ${{ github.workspace }}/target/jufeng-backend-prod.jar
          target: /root/jufeng
          strip_components: 6
      - name: Run Java Service Of jufeng-back on HW Server
        uses: fifsky/ssh-action@master
        with:
          command: supervisorctl status jufeng-back | awk '{print $2}' | while read line; do if [ $line == 'RUNNING' ]; then supervisorctl restart jufeng-back;else supervisorctl start jufeng-back; fi done
          host: ${{ secrets.HW_TEST_SERVER }}
          user: ${{ secrets.HW_SERVER_USERNAME }}
          pass: ${{ secrets.HW_SERVER_PWD }}
          args: "-tt"

